### ISSUE TITLE
Failed to transcode with FFmpeg

### ISSUE THREAD

**Issue by Kuropski** [rheaton/carrierwave-video#46] opened 2016-11-08 13:55 UTC
I got error "Completed 422 Unprocessable Entity, ActiveRecord::RecordInvalid (Validation failed: Source Failed to transcode with FFmpeg. Check ffmpeg install and verify video is not corrupt or cut short. Original error: ArgumentError)" anyone can help?

**Comment by isuPatches** [comment] 2017-01-24 05:33
I am seeing the same thing

`fmpeg version N-78176-gb340bd8 Copyright (c) 2000-2016 the FFmpeg developers`

 ```
 carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    carrierwave-video (0.5.6)
      carrierwave
      streamio-ffmpeg
```
`
Error while encoding video: Failed to transcode with FFmpeg. Check ffmpeg install and verify video is not corrupt or cut short. Original error: ArgumentError`

**Comment by alexwiththescar** [comment] 2017-03-01 09:43
Same +1, Any ideas?

**Comment by Senegal** [comment] 2017-04-14 12:52
@Kuropski @alexwiththescar 
+1. no solution?

**Comment by alexwiththescar** [comment] 2017-04-14 12:54
Did not have time to look into root cause, used Paperclip for Video

**Comment by Senegal** [comment] 2017-04-14 12:55
I see. thanks!

2017-04-14 19:54 GMT+07:00 alexwiththescar <notifications@github.com>:

**Comment by rafaltrojanowski** [comment] 2017-11-14 09:15
Related #44 Locked streamio-ffmpeg to 2.0.0 as a workaround.

**Comment by phylor** [comment] 2017-12-27 20:29
PR https://github.com/rheaton/carrierwave-video/pull/45 fixes this.

Until that is merged and released, you could pull the gem directly from the PR:

```
gem 'carrierwave-video', git: 'https://github.com/ingooooooo/carrierwave-video.git'
```

**Comment by mabid** [comment] 2017-12-28 08:11
@phylor using your PR i get this error

TypeError (no implicit conversion of Array into String):

```ruby

   process :encode

    def encode
      encode_video(:mp4, custom: '-acodec copy -vcodec copy -f mp4 -movflags faststart')
    end

```

**Comment by phylor** [comment] 2017-12-28 18:17
@mabid The PR is from @ingooooooo, I'm solely advertising it here :)

Try to hand your custom options as an array:

```
process :encode

    def encode
      encode_video(:mp4, custom: %w(-acodec copy -vcodec copy -f mp4 -movflags faststart))
    end
```

This is a breaking change due to an underlying change in `streamio-ffmpeg`. One could argue that we should keep the custom attribute as a string and convert it into an array for the underlying implementation.

**Comment by rheaton** [comment] 2018-02-14 21:43
I accepted your change, this will break existing installs. I've updated the readme.

**Closed by rheaton** 2018-02-14 21:43 UTC

**Comment by phylor** [comment] 2018-02-15 08:11
@rheaton Cool, thank you!
